In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]
stringList = ["apple", "orange"]

In [4]:
print(myList)


[1, 2, 3, 4, 5]


In [5]:
type(myList)

list

In [6]:
#dir(np)

In [7]:
#help(np)

In [8]:
arr = np.array(myList)

In [9]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#shape of the array
arr.shape

(5,)

In [11]:
arr.size

5

In [12]:
my_list1=[1,3,5,7,9]
my_list2=[2,4,6,8,7]
my_list3=[9,8,7,6,5]

arr = np.array([my_list1,my_list2,my_list3])

In [13]:
arr

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 7],
       [9, 8, 7, 6, 5]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(3, 5)

In [16]:
arr.size

15

In [17]:
my_list1=[1,2,3,4,5]
arr = np.array(my_list1)

In [18]:
print(arr[1])

2


In [19]:
print("The third element is", arr[2])

The third element is 3


In [20]:
# Slicing 2-D Arrays
my_list1=[1,3,5,7,9]
my_list2=[2,4,6,8,7]
my_list3=[9,8,7,6,5]

arr = np.array([my_list1,my_list2,my_list3])

In [21]:
arr

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 7],
       [9, 8, 7, 6, 5]])

In [22]:
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  3


In [23]:
print(arr[1,4])

7


In [24]:
valArr = np.array([[1,2,3],[4,5,6]])     #create a 2D array
#print the variabe
#get shape
#get size
#index: first row first element
#index: second row third element

In [25]:
print(valArr)
print("\n")
print('printing the shape: ',valArr.shape,"\n")
print('printing the size: ',valArr.size,"\n")
print('indexing 1st row 1st element: ',valArr[0,0],"\n")
print('indexing 2nd row 3rd element: ',valArr[1,2],"\n")

[[1 2 3]
 [4 5 6]]


printing the shape:  (2, 3) 

printing the size:  6 

indexing 1st row 1st element:  1 

indexing 2nd row 3rd element:  6 



In [26]:
#Negative Indexing

myList = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(myList)
print(arr)

valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]


In [27]:
valArr[1,-2]

5

In [28]:
#Numpy array slicing

myList = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(myList)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
#arr[start:end]
arr[0:5]

array([1, 2, 3, 4, 5])

In [30]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[:5]

array([1, 2, 3, 4, 5])

In [32]:
arr[-3:-1]

array([8, 9])

In [33]:
arr[1::3]

array([2, 5, 8])

In [34]:
arr[::2]

array([1, 3, 5, 7, 9])

In [35]:
my_list1=[1,3,5,7,9]
my_list2=[2,4,6,8,7]
my_list3=[9,8,7,6,5]

arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 3 5 7 9]
 [2 4 6 8 7]
 [9 8 7 6 5]]


In [36]:
arr[1:,:]

array([[2, 4, 6, 8, 7],
       [9, 8, 7, 6, 5]])

In [37]:
arr[:,:]

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 7],
       [9, 8, 7, 6, 5]])

In [38]:
#Arange Function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [41]:
# Linspace
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [43]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [44]:
arr = np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [45]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [46]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(".......")
print(y)

[[1 2]
 [3 4]]
.......
[[5 6]
 [7 8]]


In [47]:
x+y

array([[ 6,  8],
       [10, 12]])

In [48]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [49]:
x-y

array([[-4, -4],
       [-4, -4]])

In [50]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [51]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [53]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8],[8,9]])

x.shape



(2, 2)

In [54]:
y.shape

(3, 2)

In [55]:
x+y

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
# Floor Ceil Round
x = np.array([[1.5,2.5],[3.5,4.3]],dtype=np.float64)

x

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

In [ ]:
np.round(x)

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

In [ ]:
np.sum(x,axis=0)

In [ ]:
np.sum(x,axis=1)

In [ ]:
x.T

In [56]:
arr = np.array([1, 2, 3, 4, 5])
x = arr


print(arr)


[1 2 3 4 5]


In [57]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [60]:
#Numpy array reshaping
arr = np.arange(1,13)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
arr.shape

(12,)

In [63]:
arr_new = arr.reshape(3,4)
arr_new

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
# Iterating arrays
arr = np.arange(1,7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [68]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [69]:
arr1

array([[1, 2],
       [3, 4]])

In [70]:
arr2

array([[5, 6],
       [7, 8]])